### ISSUE TITLE
Media Session Handler User-Agent string not to specification

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-media-session-handler#24]
# Background context

In TS 26.512 V17.6.0 (2023-06), clause 6.2.3.2.2 is amended to specify more tightly the `User-Agent` header to be included in requests at reference point M5. It has always specified that a 5GMS-specific first _product_ token should be present, but now specifies that this should be suffixed with at least the 3GPP release number.

The following examples are given to illustrate the range of flexibility:

> EXAMPLE 1:	`5GMSMediaSessionHandler/17.5.0 (build1536) lib5gmsclient/0.3.1`
> EXAMPLE 2:	`5GMSMediaSessionHandler/17`

# Bug description

The current implementation of the Media Session Handler emits the following non-compliant value:

`User-Agent: okhttp/3.14.9`

# Proposed remedy

Change the `User-Agent` string to prefix the current value with the 5GMS-specified _product_ token:

`User-Agent: 5GMSMediaSessionHandler/17 okhttp/3.14.9`

**Comment by dsilhavy** [comment]
Implemented in the two linked PRs. The header looks like this:

`'user-agent': '5GMSMediaSessionHandler/17 okhttp/3.14.9'`
