### ISSUE TITLE
QoE Metrics Reporting - Reporting Sample Percentage

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-media-session-handler#26]
# Feature description
TS 26.512 specifies a `samplePercentage` that is part of the M1 `MetricsReportingConfiguration` resource and defines the proportion of media streaming sessions for which metrics shall be reported, expressed as a floating point value between 0.0 and 100.0.

If not specified, reports shall be sent for all sessions.

The concrete behavior can be derived from clause 4.8.2 which defines a similar behavior for consumption reporting:

> The Media Session Handler shall first determine whether consumption reporting is active for the session. The determination shall be based on the `samplePercentage` attribute specified in the consumption reporting configuration. When the `samplePercentage` is not present or its value is 100, consumption reporting is active for the session. If the `samplePercentage` is less than 100, the Media Session Handler generates a random number which is uniformly distributed in the range 0 to100; consumption reporting is active for the session when the generated random number is of a lower value than the `samplePercentage` value.

# Suggested solution
Only start the interval timer that requests the desired metrics periodically if the above condition is true.

**Comment by rjb1000** [comment]
Sounds good, @dsilhavy.

My interpretation is that the condition has to be computed anew at the start of each media streaming session.

**Comment by dsilhavy** [comment]
Implemented according to the description in #20. The condition is re-evaluated for each streaming session
