### ISSUE TITLE
5GMS - Media Session Handler - Consumption Collection & Reporting

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-media-session-handler#3]
**Feature description**
Executes the collection of content consumption measurement logs from the Media Player and sending of consumption reports to a 5GMSd AF about the currently consumed media within the available presentation, about the UE capabilities and about the environment of the media session for potential transport optimizations by the network or consumption report analysis.

**Relevant specifications and corresponding sections**
[26.501 - 5G Media Streaming (5GMS); General description and architecture (Release 17)](https://www.3gpp.org/ftp/Specs/archive/26_series/26.501)
[26.512 - 5G Media Streaming (5GMS); Protocols (Release 17)](https://www.3gpp.org/ftp/Specs/archive/26_series/26.512)

**Comment by dsilhavy** [comment]
Some questions that did arise during the implementation:

* What value does `duration` hold in case the Representation referenced in `mediaConsumed` is still playing? 
* Should the last selected `ConsumptionReportingUnit` be reported until a new Representation is selected? Otherwise, the `duration` can only be specified once.
* What is meant by "time-ordered list of UE location(s)" in the description of `locations`?
* Why do we have to report the IP address and the port number of the endpoint used to access the media consumed? Why not simply report the request URL as generated by the media player (DNS name) ? How should this information be derived?


Example of the consumption report as generated by #40 

````json
{
  "mediaPlayerEntry": "https://dash.akamaized.net/envivio/EnvivioDash3/manifest.mpd",
  "reportingClientId": "4bca85f1-21ac-4233-a665-b6a07a84c5be",
  "consumptionReportingUnits": [
    {
      "mediaConsumed": "v7_257",
      "mediaEndpointAddress": null,
      "startTime": "2023-09-26T16:22:51Z",
      "duration": 0,
      "locations": null
    },
    {
      "mediaConsumed": "v4_258",
      "mediaEndpointAddress": null,
      "startTime": "2023-09-26T16:22:51Z",
      "duration": 0,
      "locations": null
    }
  ]
}
````

**Comment by rjb1000** [comment]
> What value does duration hold in case the Representation referenced in _mediaConsumed_ is still playing?

In the absence of a clear specification, maybe the last Consumption Reporting Unit in the consumption report describes the media currently being consumed. I would expect this to specify how long the Representation has been playing.

>  Should the last selected ConsumptionReportingUnit be reported until a new Representation is selected? Otherwise, the duration can only be specified once.

If the same Representation is still being consumed when it's time to send the next consumption report, I would say that this Consumption Reporting Unit is repeated as the first one in that next report, with the same _startTime_ as before, but a longer _duration_.

The recipient of the consumption reports could then apply some queue compression to ignore all but the last Consumption Reporting Unit with the same start time.

Please raise a Specification issue asking for both of these points to be clarified in TS 26.512.

**Comment by rjb1000** [comment]
> What is meant by "time-ordered list of UE location(s)" in the description of locations?

When the _ServiceAccessInformation.clientConsumptionReporting.locationReporting_ flag is set, ConsumptionReportingUnit.locations is an array of locations where the UE was when this Consumption Reporting Unit was logged by the 5GMS Client. The _TypedLocation_ type allows a number of different types of location to be reported.

I suppose the Media Stream Handler will need to invoke an suitable Android API to log this information during a media streaming session.

**Comment by dsilhavy** [comment]
> * Should the last selected `ConsumptionReportingUnit` be reported until a new Representation is selected? Otherwise, the `duration` can only be specified once.



> > What value does duration hold in case the Representation referenced in _mediaConsumed_ is still playing?
> 
> In the absence of a clear specification, maybe the last Consumption Reporting Unit in the consumption report describes the media currently being consumed. I would expect this to specify how long the Representation has been playing.
> 
> > Should the last selected ConsumptionReportingUnit be reported until a new Representation is selected? Otherwise, the duration can only be specified once.
> 
> If the same Representation is still being consumed when it's time to send the next consumption report, I would say that this Consumption Reporting Unit is repeated as the first one in that next report, with the same _startTime_ as before, but a longer _duration_.
> 
> The recipient of the consumption reports could then apply some queue compression to ignore all but the last Consumption Reporting Unit with the same start time.
> 
> Please raise a Specification issue asking for both of these points to be clarified in TS 26.512.

Added a standards issue here: https://github.com/5G-MAG/Standards/issues/90. Current implementation is documented here: https://github.com/5G-MAG/rt-5gms-media-stream-handler/issues/52

**Comment by dsilhavy** [comment]
@rjb1000 Are you ok with closing this issue as we have detailed discussions here:

* https://github.com/5G-MAG/rt-5gms-media-stream-handler/issues/54
* https://github.com/5G-MAG/rt-5gms-media-stream-handler/issues/56
