### ISSUE TITLE
License and copyright notes

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-media-session-handler#35]
## Description
As we are planning to provide the APK of the 5GMSd Media Session Handler for download via Linode or Github we would like to add the license and the copyright notes to the app. This can be done by adding a button for each of the items and showing the information after the user clicks on the button.

**Comment by rjb1000** [comment]
Just checking: does the Media Session Handler have a GUI when packaged as a standalone APK?

I assumed (perhaps wrongly) that it would just get installed as a background service with no GUI.

**Comment by dsilhavy** [comment]
Yes, it has a GUI but without any elements so far except for the version number.

**Comment by dsilhavy** [comment]
Addressed in #39
